token_limit: 20000
use_gitignore: true
output_dir: documentation
max_content_length: 5000

# Commit feature configuration
commit:
  # LLM configuration
  llm:
    model: groq/llama-3.1-8b-instant
    # IMPORTANT: Do NOT add API keys here. Use environment variables or .env files instead.

  # Commit convention settings
  convention:
    types:
      - feat     # New feature
      - fix      # Bug fix
      - docs     # Documentation
      - style    # Formatting, missing semicolons, etc.
      - refactor # Code change that neither fixes a bug nor adds a feature
      - perf     # Performance improvement
      - test     # Adding or updating tests
      - build    # Build system or external dependencies
      - ci       # CI configuration
      - chore    # Other changes that don't modify src or test files

    # Optional scopes for your project (derived from directory structure if empty)
    scopes: []

    # Maximum length for commit message subject line
    max_length: 72
