token_limit: 0
use_gitignore: true
output_dir: documentation
max_content_length: 0

# Commit feature configuration
commit:
  # LLM configuration
  llm:
    model: meta-llama/llama-4-scout-17b-16e-instruct
    provider: groq
    # IMPORTANT: Do NOT add API keys here. Use environment variables or .env files instead.

  # Commit convention settings
  convention:
    types:
      - feat     # New feature
      - fix      # Bug fix
      - docs     # Documentation
      - style    # Formatting, missing semicolons, etc.
      - refactor # Code change that neither fixes a bug nor adds a feature
      - perf     # Performance improvement
      - test     # Adding or updating tests
      - build    # Build system or external dependencies
      - ci       # CI configuration
      - chore    # Other changes that don't modify src or test files

    # Optional scopes for your project (derived from directory structure if empty)
    scopes: []

    # Maximum length for commit message subject line
    max_length: 72

  # Semantic chunking configuration
  semantic:
    # Threshold for semantic similarity (0.0-1.0)
    # Higher values require chunks to be more similar to be grouped
    similarity_threshold: 0.7

    # Embedding model for code similarity
    # Options: "flax-sentence-embeddings/st-codesearch-distroberta-base" (default),
    #          "microsoft/codebert-base", "all-MiniLM-L6-v2" (faster)
    embedding_model: "flax-sentence-embeddings/st-codesearch-distroberta-base"

    # Fallback model if primary model fails to load
    fallback_model: "all-MiniLM-L6-v2"

    # Language-specific settings
    languages:
      # Recognized code files for semantic parsing
      extensions:
        - py    # Python
        - js    # JavaScript
        - ts    # TypeScript
        - java  # Java
        - kt    # Kotlin
        - go    # Go
        - c     # C
        - cpp   # C++
        - cs    # C#
        - rb    # Ruby
        - php   # PHP
        - swift # Swift

      # Cache embeddings to improve performance on subsequent runs
      cache_embeddings: true

      # Maximum size of embedding cache (number of entries)
      max_cache_size: 1000
