version: "3"

vars:
  SRC_DIR: src
  TESTS_DIR: tests
  COV_MODULE: src/codemap

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task -l

  lint:
    desc: Run all linting checks
    cmds:
      - task: lint:ruff
      - task: lint:pylint
      - task: lint:pyright

  lint:ruff:
    desc: Run ruff linter
    cmds:
      - ruff check {{.SRC_DIR}} {{.TESTS_DIR}}

  lint:fix:
    desc: Run ruff linter with auto-fix
    cmds:
      - ruff check --fix {{.SRC_DIR}} {{.TESTS_DIR}}

  lint:fix-unsafe:
    desc: Run ruff linter with unsafe auto-fixes
    cmds:
      - ruff check --fix --unsafe-fixes {{.SRC_DIR}} {{.TESTS_DIR}}

  lint:pylint:
    desc: Run pylint
    cmds:
      - pylint {{.SRC_DIR}}

  lint:pyright:
    desc: Run pyright type checker
    cmds:
      - pyright {{.SRC_DIR}}

  test:
    desc: Run all tests
    cmds:
      - task: test:pytest

  test:pytest:
    desc: Run pytest only
    cmds:
      - pytest {{.TESTS_DIR}} -n logical

  test:coverage:
    desc: Run tests with coverage analysis
    cmds:
      - pytest --cov={{.COV_MODULE}} --cov-report=term-missing {{.TESTS_DIR}} -n logical

  test:coverage:xml:
    desc: Run tests with coverage analysis and generate XML report
    cmds:
      - pytest --cov={{.COV_MODULE}} --cov-branch --cov-report=xml {{.TESTS_DIR}} -n logical

  ci:
    desc: Run all checks and tests
    cmds:
      - task: lint
      - task: test:coverage

  ci:full:
    desc: Run all checks and tests in CI mode
    cmds:
      - task: lint
      - task: test:coverage:xml
