"""Git functionality for CodeMap."""

from .commit import (
    ChunkAction,
    ChunkResult,
    CommitCommand,
    CommitUI,
    DiffChunk,
    DiffSplitter,
    SplitStrategy,
)
from .git import GitWrapper
from .utils import (
    GitDiff,
    GitError,
    PullRequest,
    branch_exists,
    checkout_branch,
    commit,
    create_branch,
    create_pull_request,
    generate_pr_description_from_commits,
    generate_pr_title_from_commits,
    get_commit_messages,
    get_current_branch,
    get_default_branch,
    get_existing_pr,
    get_repo_root,
    get_staged_diff,
    get_unstaged_diff,
    get_untracked_files,
    push_branch,
    stage_files,
    suggest_branch_name,
    unstage_files,
    update_pull_request,
)

__all__ = [
    "ChunkAction",
    "ChunkResult",
    "CommitCommand",
    "CommitUI",
    "DiffChunk",
    "DiffSplitter",
    "GitDiff",
    "GitError",
    "GitWrapper",
    "PullRequest",
    "SplitStrategy",
    "branch_exists",
    "checkout_branch",
    "commit",
    "create_branch",
    "create_pull_request",
    "generate_pr_description_from_commits",
    "generate_pr_title_from_commits",
    "get_commit_messages",
    "get_current_branch",
    "get_default_branch",
    "get_existing_pr",
    "get_repo_root",
    "get_staged_diff",
    "get_unstaged_diff",
    "get_untracked_files",
    "push_branch",
    "stage_files",
    "suggest_branch_name",
    "unstage_files",
    "update_pull_request",
]
